apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-receive-controller
  namespace: ingestion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thanos-receive-controller
  namespace: ingestion
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - watch
  - update
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-receive-controller
  namespace: ingestion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thanos-receive-controller
subjects:
- kind: ServiceAccount
  name: thanos-receive-controller
  namespace: ingestion
---
apiVersion: v1
data:
  hashrings.json: |
    [
        {
            "hashring":"default",
            "tenants":[]
        }
    ]
kind: ConfigMap
metadata:
  name: thanos-receive-config-base
  namespace: ingestion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-receive-controller
  namespace: ingestion
  labels:
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/component: kubernetes-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive-controller
      app.kubernetes.io/component: kubernetes-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-receive-controller
        app.kubernetes.io/component: kubernetes-controller
    spec:
      containers:
      - name: thanos-receive-controller
        image: quay.io/observatorium/thanos-receive-controller
        args:
        - --configmap-name=thanos-receive-config-base
        - --configmap-generated-name=thanos-receive-config-generated
        - --file-name=hashrings.json
        - --namespace=$(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccount: thanos-receive-controller
