apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
  labels:
    app: thanos-receive
    controller.receive.thanos.io: thanos-receive-controller
    controller.receive.thanos.io/hashring: default
spec:
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: thanos-receive
  serviceName: thanos-receive
  template:
    metadata:
      labels:
        app: thanos-receive
    spec:
      serviceAccountName: thanos-receive
      containers:
      - name: thanos-receive
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/thanos/thanos:v0.13.0
        args:
        - receive
        - --tsdb.path=/data/remote-write-receive-data
        - --log.level=debug       
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/prometheus/gcs-bucket-secret.yaml
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - name: remote-write
          containerPort: 19291
        - name: grpc
          containerPort: 10901
        - name: http
          containerPort: 10902
        volumeMounts:
        - name: gcs-bucket-credentials
          mountPath: /etc/prometheus
          readOnly: true
        - name: remote-write-data
          mountPath: /data/remote-write-receive-data
      volumes:
      - name: gcs-bucket-credentials
        secret:
          secretName: gcs-bucket-credentials
  volumeClaimTemplates:
  - metadata:
      name: remote-write-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      volumeMode: Filesystem
