apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-write
  labels:
    app: thanos-receive-write
spec:
  ports:
  - name: grpc
    port: 10901
    protocol: TCP
    targetPort: grpc
  - name: remote-write
    port: 19291
    protocol: TCP
    targetPort: remote-write
  - name: http
    port: 10902
    targetPort: http
  selector:
    app: thanos-receive
  type: ClusterIP
